version: "3.5"
services:

  eventstore:
    image: eventstore/eventstore:22.6.0-buster-slim
    restart: always
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=True
      - EVENTSTORE_DISCOVER_VIA_DNS=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=True
      - EVENTSTORE_INSECURE=true
    ports:
      - 2113:2113
    volumes:
      - ./local/eventstore/certs:/certs

  events-producer:
    image: events-producer:latest
    ports:
      - 8081:8080

  app:
    build: ./app
    ports:
      - 8080:80

  proxy:
    build: ./proxy
    ports:
      - 80:80
    depends_on:
      - app
      - events-producer
